export { default as useArmor } from './useArmor'
export { default as useDeviceWidth } from './useDeviceWidth'
export { default as useHeadingSize } from './useHeadingSize'
export { default as useItems } from './useItems'
export { getApiBase, getLocalStorageJSON } from './utilities'